# syntax version.
version: "3.7"

# services list.
services:
  # base image
  alpine-base:
    image: "550419038/hyperf:${PHP_VERSION}-alpine-v${ALPINE_VERSION}-base"
    build:
      context: "${PHP_VERSION}/alpine/base"
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}

  # swoole image
  alpine-swoole:
    image: "550419038/hyperf:${PHP_VERSION}-alpine-v${ALPINE_VERSION}-swoole${SPEC}-${SW_VERSION}"
    build:
      context: "${PHP_VERSION}/alpine/swoole"
      dockerfile: "Dockerfile${SPEC}"
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        SW_VERSION: ${SW_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
        PHP_BUILD_VERSION: ${PHP_BUILD_VERSION}

  # swow image
  alpine-swow:
    image: "550419038/hyperf:${PHP_VERSION}-alpine-v${ALPINE_VERSION}-swow${SPEC}-${SW_VERSION}"
    build:
      context: "${PHP_VERSION}/alpine/swow"
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        SW_VERSION: ${SW_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
        PHP_BUILD_VERSION: ${PHP_BUILD_VERSION}

  # dev image
  alpine-dev:
    image: "550419038/hyperf:${PHP_VERSION}-alpine-v${ALPINE_VERSION}-dev"
    build:
      context: "${PHP_VERSION}/alpine/dev"
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
        PHP_BUILD_VERSION: ${PHP_BUILD_VERSION}
